application: el-camino
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1d"

handlers:
- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /static/*
  static_dir: static/

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest


env_variables:
  latest_static_version: "2014.4.21.4"

